@isTest
public class TestUtil {
    public static final String TEST_PRIVATE_KEY =
        'MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANMZAwJZnyXAgyZ8\n' +
        'vLtXZIxKDEwQIU0gNEHfIwB6+uuiK7YPfr80wAMEGD1/UlDy9NSG0/CLhc8BsL43\n' +
        '29zfY8zh3FhmP8W/RAkdzcbhgxdl6D+SwWXzs+zfLvOrhTQO9FYHiX+yXmCPBJ6t\n' +
        '01+Zc+MMRfuRzP3WmbciP3e1lyJlAgMBAAECgYB2bZ7Jj7wAMvug+PPs6j+HkPdL\n' +
        'KPV1zm5i0itR1qy0yztYnWLPJGngh0iOH8LvlQ4TuTxnw+6izuD4JmBbjpvuzW0n\n' +
        'ys+nB3oHbZZQ/+bPkpVD6RqLOFBW+J/QIbBaRH0aapeypNue3jSuhHYpV6s8E5Ji\n' +
        'L4/jLR3xxyZDuwmatQJBAPIvkiyUN63q/Q4aR8/gyv5tVlNdcGLKuJxAx3Yv2PQP\n' +
        'RwPVHUWiVuAaEqc5uSbdry1lkXsSrOtd4NSsBH9dHJsCQQDfI3zqH9kh56b1Kvdk\n' +
        'Ew6guN6M3Kui63N9lhFLMzmGValBejyc8V/gZZEpzmFtSLc9C3lNhG0VTxNzCtWf\n' +
        'Fyz/AkAp2bibxX0dq7bRAg+Yx5Kshr5dJ49tMvTV44fUT45hFmbCLciiKNx0W20P\n' +
        'wrTRF4vW/281YlPJVG6usY8RZ0izAkAxEdDKe654MkUY7RXyP+6bkYv/Vhe4gCap\n' +
        'm3K6Is2nqPbLm2Hw8XOwGSXPF799FNyW5AsM7O5AHV+dkOhhT+tpAkEA0RZqobF5\n' +
        'ITtwIgKVEFsRKZUCOdsgVProiKNOty6u1rRbDsRhjo2hrmg9KVSGuyBm0V5pSA5T\n' +
        'nhsqtYSLsdaklw==';
    public static final String TEST_HOST = 'https://Eqc5uSbdry1lkXsSrOt.does-not-exist.envato.net';
    public static final String TEST_KEY_ID = 'test.test.test';
}